### ISSUE TITLE
Missing Documents

### ISSUE THREAD

**Issue by GrantPDonnelly** [rotsehub/rotseana#2]
So as to not exacerbate the organization issue on rotsehub, please reply to this with the name and description of any document you have that will need to be uploaded. Provide any other information you have.

We can then discuss the most effective way to organize everything before anything else gets uploaded.

**Comment by rkehoe** [comment]
@GrantPDonnelly Can you indicate if this issue has been resolved?  Generally, we want to avoid Issues sitting around for many months, and resolve them promptly.  If this one is resolved, please close it.  I can come by later and delete any closed issues.

If this issue is still open for a reason, then please comment here on the status and what still is being requested.  Please be as specific as you can.  Thx.

**Comment by GrantPDonnelly** [comment]
As the updated versions of the ceph_tools programs have been merged, along with new documentation for it, I am closing this issue.
